// <auto-generated />
using ClinicBookingg.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicBookingg.Migrations
{
    [DbContext(typeof(ClinicContext))]
    [Migration("20260814213459_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicBookingg.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAcceptingPatients")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Expert cardiologist.",
                            IsAcceptingPatients = true,
                            Name = "Dr. Amina Farid",
                            Specialty = "Cardiology",
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Cosmetic & medical dermatology.",
                            IsAcceptingPatients = false,
                            Name = "Dr. Youssef Hany",
                            Specialty = "Dermatology",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Pediatrician caring for children.",
                            IsAcceptingPatients = true,
                            Name = "Dr. Layla Mahmoud",
                            Specialty = "Pediatrics",
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Senior orthopedic surgeon.",
                            IsAcceptingPatients = true,
                            Name = "Dr. Omar Nasser",
                            Specialty = "Orthopedics",
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 5,
                            Bio = "General and cosmetic dentistry.",
                            IsAcceptingPatients = true,
                            Name = "Dr. Salma Ibrahim",
                            Specialty = "Dentistry",
                            YearsOfExperience = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
