// <auto-generated />
using ClinicBookingg.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicBookingg.Migrations
{
    [DbContext(typeof(ClinicContext))]
    partial class ClinicContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicBookingg.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAcceptingPatients")
                        .HasColumnType("bit");

                    b.Property<string>("LicenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Expert cardiologist.",
                            ImageUrl = "doc1.jpg",
                            IsAcceptingPatients = true,
                            LicenceNumber = "LIC-1001",
                            Name = "Dr. Amina Farid",
                            Phone = "01012345678",
                            Specialty = "Cardiology",
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Cosmetic & medical dermatology.",
                            ImageUrl = "doc2.jpg",
                            IsAcceptingPatients = true,
                            LicenceNumber = "LIC-1002",
                            Name = "Dr. Youssef Hany",
                            Phone = "01123456789",
                            Specialty = "Dermatology",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Pediatrician caring for children.",
                            ImageUrl = "doc3.jpg",
                            IsAcceptingPatients = true,
                            LicenceNumber = "LIC-1003",
                            Name = "Dr. Layla Mahmoud",
                            Phone = "01234567890",
                            Specialty = "Pediatrics",
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Senior orthopedic surgeon.",
                            ImageUrl = "doc4.jpg",
                            IsAcceptingPatients = true,
                            LicenceNumber = "LIC-1004",
                            Name = "Dr. Omar Nasser",
                            Phone = "01545678901",
                            Specialty = "Orthopedics",
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 5,
                            Bio = "General and cosmetic dentistry.",
                            ImageUrl = "doc5.jpg",
                            IsAcceptingPatients = true,
                            LicenceNumber = "LIC-1005",
                            Name = "Dr. Salma Ibrahim",
                            Phone = "01098765432",
                            Specialty = "Dentistry",
                            YearsOfExperience = 6
                        });
                });

            modelBuilder.Entity("ClinicBookingg.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@clinic.com",
                            PasswordHash = "AQAAAAIAAYagAAAAENNmfY+q2gHgChayZ3UCILVDym57loMTX6HgXpTNQTCT3JxdWRtVcO2rqz7V36VFOw==",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "rec1@clinic.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEDFALzt0tnelzv5POsk4q1KzO/ZGftxurBpdyYvjhyxLrj37xzD4gFgIF5KU89JhjA==",
                            Role = "Receptionist"
                        },
                        new
                        {
                            Id = 3,
                            Email = "rec2@clinic.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEC/eWPyIZAAHTtBBAqaVuB9xlh5cri++IlOvkiXw3q0XnEAatval8GCylTsIRT/yjw==",
                            Role = "Receptionist"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
